name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  ubuntu-latest:
    name: Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}}

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Pack
        run: dotnet pack --configuration Release --no-build --output output /property:Version="${{ steps.meta.outputs.version }}"
      - name: Push
        run: dotnet nuget push output/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_AUTH_TOKEN --skip-duplicate
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}